const LIVE_CAREERS='https://www.aknorthstar.com/careers-culture';
const roles={
  'systems-engineer':{
    title:'Systems Engineer',tags:['Remote','Full-time','Engineering','Clearance-oriented'],department:'Technology & Engineering',location:'Remote / hybrid concept',focus:'Secure systems engineering',lead:'Design, integrate, and advance secure systems that support complex federal missions in distributed environments.',description:'This concept role profile shows how Alaska Northstar Resources could present a systems engineering opportunity in a clear, mission-focused format. The role centers on architecture, integration, sustainment, reliability, and secure operations across complex technical environments.',responsibilities:['Lead systems engineering activities across the delivery lifecycle','Develop and maintain system architectures, interfaces, diagrams, and technical requirements','Integrate hardware, software, cloud, and network components into cohesive solutions','Support secure design reviews, system hardening, troubleshooting, and operational readiness','Collaborate with cybersecurity, cloud, application, network, and mission stakeholders'],qualifications:['Degree or equivalent experience in systems engineering, computer science, electrical engineering, or a related technical field','Experience designing, integrating, or sustaining complex enterprise or mission systems','Working knowledge of networking, cloud infrastructure, cybersecurity, and automation concepts','Ability to communicate technical tradeoffs clearly across multidisciplinary teams'],preferred:['Experience in federal or DoD mission environments','Familiarity with RMF, STIGs, DevSecOps, Zero Trust, or secure architecture frameworks','Linux, virtualization, cloud, containerization, or infrastructure automation experience','Relevant engineering or security certifications']
  },
  'cybersecurity-engineer':{
    title:'Cybersecurity Engineer',tags:['Hybrid / Remote','Full-time','Cybersecurity','Mission Assurance'],department:'Cybersecurity',location:'Hybrid / remote concept',focus:'Mission security & compliance',lead:'Protect mission systems through secure architecture, compliance engineering, continuous monitoring, and practical remediation.',description:'This concept profile demonstrates a cybersecurity role focused on reducing mission risk while helping delivery teams move efficiently through federal security requirements. Work spans architecture, assessment, hardening, monitoring, documentation, and remediation.',responsibilities:['Translate security requirements into practical technical controls and engineering tasks','Support RMF, A&A, STIG implementation, vulnerability management, and compliance evidence','Partner with cloud, network, and software teams to build security into delivery workflows','Investigate findings, prioritize remediation, and track risk to closure','Improve repeatability through security automation and Compliance as Code practices'],qualifications:['Experience in cybersecurity engineering, information assurance, or security operations','Working knowledge of federal security controls, system hardening, and vulnerability management','Ability to analyze technical risk and recommend practical mitigations','Strong written communication for technical findings and compliance artifacts'],preferred:['RMF, NIST 800-53, DISA STIG, or Zero Trust experience','Security+, CISSP, CCSP, or comparable certification','Cloud security experience across AWS, Azure, or GCP','Scripting or automation experience for security operations']
  },
  'software-engineer':{
    title:'Software Engineer',tags:['Hybrid','Full-time','Applications','Backend'],department:'Application Services',location:'Hybrid concept',focus:'Secure application delivery',lead:'Build secure, scalable applications and integrations that help government teams deliver mission outcomes faster.',description:'This concept role profile presents a software engineering position centered on modern application delivery for federal environments. The work emphasizes maintainability, secure engineering, systems integration, testing, and collaboration with DevSecOps teams.',responsibilities:['Design and implement secure application services, APIs, and backend components','Collaborate on architecture, data models, integration patterns, and technical standards','Write automated tests and participate in code review and quality assurance','Integrate application delivery into CI/CD and DevSecOps workflows','Troubleshoot production issues and improve reliability and observability'],qualifications:['Professional software development experience in a modern programming language','Understanding of APIs, databases, application security, testing, and source control','Experience working in collaborative Agile or iterative delivery teams','Ability to reason about scalability, reliability, maintainability, and system integration'],preferred:['Federal, DoD, or regulated-environment delivery experience','Cloud-native application development experience','Containers, Kubernetes, CI/CD, or infrastructure automation familiarity','Experience with secure software development and supply-chain controls']
  },
  'devsecops-engineer':{
    title:'DevSecOps Engineer',tags:['Remote','Full-time','DevSecOps','Cloud'],department:'Application / Cloud Services',location:'Remote concept',focus:'Secure delivery automation',lead:'Automate secure software delivery pipelines and strengthen platforms from build through deployment and sustainment.',description:'This concept role demonstrates how ANR could present a DevSecOps opportunity focused on the intersection of software, cloud, infrastructure, and security. The role is built around faster delivery without sacrificing mission assurance.',responsibilities:['Build and maintain CI/CD pipelines for secure and repeatable application delivery','Automate infrastructure, platform configuration, testing, and policy checks','Integrate security scanning and compliance controls into delivery workflows','Support container, cloud, and Kubernetes-based application platforms','Partner with developers and security teams to troubleshoot and improve delivery reliability'],qualifications:['Experience with CI/CD, infrastructure automation, cloud platforms, or platform engineering','Working knowledge of Git-based workflows, containers, scripting, and modern deployment patterns','Understanding of security scanning, secrets management, and secure configuration principles','Ability to diagnose issues across application and infrastructure layers'],preferred:['AWS, Azure, Kubernetes, Terraform, Ansible, GitLab CI, GitHub Actions, or Jenkins experience','Federal DevSecOps or Platform One familiarity','Experience implementing policy or compliance checks in pipelines','Security or cloud certifications']
  }
};

const params=new URLSearchParams(location.search);let slug=params.get('role')||'systems-engineer';if(!roles[slug])slug='systems-engineer';const role=roles[slug];
const $=s=>document.querySelector(s);const fillList=(id,items)=>{const el=$(id);items.forEach(item=>{const li=document.createElement('li');li.textContent=item;el.appendChild(li)})};
document.title=`${role.title} — ANR Career Concept`;
$('#roleTitle').textContent=role.title;$('#roleLead').textContent=role.lead;$('#roleDescription').textContent=role.description;
role.tags.forEach(tag=>{const span=document.createElement('span');span.className='role-tag';span.textContent=tag;$('#roleTags').appendChild(span)});
fillList('#responsibilities',role.responsibilities);fillList('#qualifications',role.qualifications);fillList('#preferred',role.preferred);
['#factDepartment','#factDepartmentMobile'].forEach(id=>$(id).textContent=role.department);['#factLocation','#factLocationMobile'].forEach(id=>$(id).textContent=role.location);['#factFocus','#factFocusMobile'].forEach(id=>$(id).textContent=role.focus);
const similar=Object.entries(roles).filter(([key])=>key!==slug).slice(0,3);similar.forEach(([key,item])=>{const card=document.createElement('article');card.className='similar-card';card.innerHTML=`<b>${item.title}</b><small>${item.location}<br>${item.focus}</small><a href="career-role.html?role=${key}">Learn More →</a>`;$('#similarRoles').appendChild(card)});

document.querySelectorAll('.apply-primary').forEach(a=>a.href=LIVE_CAREERS);
const mobileApply=document.createElement('a');mobileApply.className='mobile-apply';mobileApply.href=LIVE_CAREERS;mobileApply.target='_blank';mobileApply.rel='noopener';mobileApply.innerHTML='Apply Now <span>→</span>';document.querySelector('.role-hero-inner').appendChild(mobileApply);
